#!/usr/bin/env bash
# Redirect to another page
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "301 Moved Permanently" >> /var/www/html/index.html

sed -i '38i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
