#!/usr/bin/env bash
# configure servers web-02 to be identical to web-01
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
sudo mkdir -p /var/www/error

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /var/www/error
sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  add_header X-Served-By $hostname;
  root /var/www/html;
  index index.html index.htm index.nginx-debian.html
}" > /etc/nginx/sites-available/default
sudo service nginx restart
