#!/usr/bin/env bash
# configure servers web-02 to be identical to web-01
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'

sudo sed -i 's/http {/&\n\tadd_header X-Served-By $hostname/' /etc/nginx/nginx.conf
sudo service nginx restart
