#!/usr/bin/env bash
# configure the load balancer on servers web-02 and web-01
sudo apt update
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt install -y haproxy=2.6.\*

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 16742-web-01 34.204.166.252:80 check\n\tserver 16742-web-02 18.205.192.79:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
