#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

i=true

while [ $i ]
do
  echo "To inifinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
